### ISSUE TITLE
About OC_toolkit_SC_EOS in system version 19.0.0

### ISSUE THREAD

**Issue by R1031018** [halop/OC_Toolkit_SC_EOS#1]
Hello, atomosphere and hekate are now compatible with system version 19.0.0, but when I try to change the max clock, the value does not change. The error code is Error Code: 2168-0001. Is there any current plan to support this?

**Comment by R1031018** [comment]
![Uploading 50CEBAEF-B2E9-41D0-A326-BB0B2523CB53.jpeg…]()

**Comment by R1031018** [comment]
atomosphere 1.8.0 available

**Comment by R1031018** [comment]
atomosphere 1.8.0 available
![Uploading ECBC57D9-F07A-4EFB-8F67-5BDDA3ADB656.jpeg…]()

**Comment by R1031018** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/2386#issuecomment-2408306021

**Comment by halop** [comment]
It will be updated once a normal AMS release is available.
